USE LOJA_01


CREATE TABLE [TABELA DE CLIENTES] (
CPF VARCHAR (11),					--PRECISA SER VARCHAR PARA O SQL NÃO TIRAR OS ZEROS DO INICIO
NOME VARCHAR (100),
[ENDEREÇO 1] VARCHAR (150),
[ENDEREÇO 2] VARCHAR (150),
BAIRRO VARCHAR (50),
CIDADE VARCHAR (50),
ESTADO VARCHAR (2),
CEP VARCHAR (8),
[DATA NASCIMENTO] DATE,
IDADE SMALLINT,
SEXO VARCHAR (1),
[LIMITE DE CREDITO] MONEY,
[VOLUME DE COMPRA] FLOAT,
[PRIMEIRA COMPRA] BIT

)


--DROP TABLE DBO.[TABELA DE PRODUTO]

CREATE TABLE [TABELA DE PRODUTOS] (
[CODIGO DO PRODUTO] INT,
[NOME DO PRODUTO] VARCHAR (50),
EMBALAGEM VARCHAR (50),
TAMANHO VARCHAR (20),
SABOR VARCHAR (20),
[PREÇO DE LISTA] MONEY
)

-- ALTERE TIPO DAS COLUNAS E RESTRIÇÕES

ALTER TABLE [TABELA DE CLIENTES]
ALTER COLUMN CPF VARCHAR (11) NOT NULL


ALTER TABLE [TABELA DE PRODUTOS]
ALTER COLUMN [CODIGO DO PRODUTO]
VARCHAR (10) NOT NULL




ALTER TABLE [TABELA DE CLIENTES]
ADD CONSTRAINT PK_CLIENTES
PRIMARY KEY CLUSTERED (CPF)


ALTER TABLE [TABELA DE PRODUTOS]
ADD CONSTRAINT PK_PRODUTOS
PRIMARY KEY CLUSTERED ([CODIGO DO PRODUTO])